---
title: "Visualization with ggplot2 and more"
format: html
---

```{r}
#| warning: false
library(readr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(janitor) # expedite cleaning and exploring data
library(scales) # scale functions for visualization
```

```{r}
escape_raw<-read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e")
```
```{r}
escape<-escape_raw %>% 
  clean_names()
escape
```
```{r}
annual_esc<-escape %>% 
  filter(species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink")) %>%#filtering for specific species within whole list of species
    mutate(year = lubridate::year(sample_date)) %>%#lubridate has us calling year function from package and extracts just the year from the date column
    group_by(species, sasap_region, year) %>%#summarizing by the categories invoked in group_by
    summarize(escapement = sum(daily_count))
```
```{r}
ggplot(data=annual_esc, mapping=aes(x=species, y=escapement))+
  geom_col(aes(fill=species))+
  geom_point()
```
```{r}
annual_esc<-annual_esc %>% 
  filter(year == 1974,species %in% c("Chum","Pink")) %>% 
  ggplot(aes(x=species, y=escapement))+
  geom_col(aes(fill=species))+
  geom_boxplot()
annual_esc
```
```{r}
library(DT)
locations<-escape %>% 
  distinct(location,latitude,longitude) %>% 
  drop_na()
```
```{r}
datatable(locations)
```
## Mapping with leaflet
```{r}
library(leaflet)
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(
    lng=~longitude,
    lat=~latitude,
    popup=~location
  )
```
```{r}
leaflet(locations) %>%
    addWMSTiles(
        "https://wms.gebco.net/mapserv?request=getmap&service=wms&BBOX=-90,-180,90,360&crs=EPSG:4326&format=image/jpeg&layers=gebco_latest&width=1200&height=600&version=1.3.0",
        layers = 'GEBCO_LATEST',
        attribution = "Imagery reproduced from the GEBCO_2022 Grid, WMS 1.3.0 GetMap, www.gebco.net"
    ) %>%
    addCircleMarkers(
        lng = ~ longitude,
        lat = ~ latitude,
        popup = ~ location,
        radius = 5,
        # set fill properties
        fillColor = "salmon",
        fillOpacity = 1,
        # set stroke properties
        stroke = TRUE,
        weight = 0.5,
        color = "white",
        opacity = 1
    )
```

